local addonName, Roth_UI = ...
local LSM = LibStub("LibSharedMedia-3.0")


--- Media registration for orb textures
LSM:Register("orb_filling", "moon", "Interface\\AddOns\\Roth_UI\\media\\orb_filling1")
LSM:Register("orb_filling", "earth", "Interface\\AddOns\\Roth_UI\\media\\orb_filling2")
LSM:Register("orb_filling", "mars", "Interface\\AddOns\\Roth_UI\\media\\orb_filling3")
LSM:Register("orb_filling", "galaxy", "Interface\\AddOns\\Roth_UI\\media\\orb_filling4")
LSM:Register("orb_filling", "jupiter", "Interface\\AddOns\\Roth_UI\\media\\orb_filling5")
LSM:Register("orb_filling", "fraktal circle", "Interface\\AddOns\\Roth_UI\\media\\orb_filling6")
LSM:Register("orb_filling", "sun", "Interface\\AddOns\\Roth_UI\\media\\orb_filling7")
LSM:Register("orb_filling", "icecream", "Interface\\AddOns\\Roth_UI\\media\\orb_filling8")
LSM:Register("orb_filling", "marble", "Interface\\AddOns\\Roth_UI\\media\\orb_filling9")
LSM:Register("orb_filling", "gradient", "Interface\\AddOns\\Roth_UI\\media\\orb_filling10")
LSM:Register("orb_filling", "bubbles", "Interface\\AddOns\\Roth_UI\\media\\orb_filling11")
LSM:Register("orb_filling", "woodpepples", "Interface\\AddOns\\Roth_UI\\media\\orb_filling12")
LSM:Register("orb_filling", "golf", "Interface\\AddOns\\Roth_UI\\media\\orb_filling13")
LSM:Register("orb_filling", "darkstar", "Interface\\AddOns\\Roth_UI\\media\\orb_filling14")
LSM:Register("orb_filling", "diablo3", "Interface\\AddOns\\Roth_UI\\media\\orb_filling15")
LSM:Register("orb_filling", "fubble", "Interface\\AddOns\\Roth_UI\\media\\orb_filling16")
LSM:Register("orb_filling", "silver", "Interface\\AddOns\\Roth_UI\\media\\orb_filling17")
LSM:Register("orb_filling", "exile", "Interface\\AddOns\\Roth_UI\\media\\orb_filling18")
LSM:Register("orb_filling", "dominion", "Interface\\AddOns\\Roth_UI\\media\\orb_filling19")
LSM:Register("orb_filling", "runes", "Interface\\AddOns\\Roth_UI\\media\\orb_filling20")
LSM:Register("orb_filling", "sigil orb", "Interface\\AddOns\\Roth_UI\\media\\orb_filling21")
LSM:Register("orb_filling", "transparent", "Interface\\AddOns\\Roth_UI\\media\\orb_transparent")
